% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{plainnat}
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Statistical Programming for the Social Sciences Using R},
  pdfauthor={Wesley Stubenbord},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Statistical Programming for the Social Sciences Using R}
\author{Wesley Stubenbord}
\date{2024-02-11}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{introduction}{%
\chapter*{Introduction}\label{introduction}}
\addcontentsline{toc}{chapter}{Introduction}

Welcome! This is the companion website for \emph{Statistical Programming for the Social Sciences Using R}, taught at the Sciences Po Reims campus for the Spring 2024 term.

This website will contain the relevant tutorials for each week's lesson as well as other resources that you may find helpful throughout the course. The syllabus, assignment submission portals, and other files can be found on the course Moodle site.

\hypertarget{an-introduction-to-r}{%
\chapter{\texorpdfstring{An Introduction to \texttt{R}}{An Introduction to R}}\label{an-introduction-to-r}}

To get started, you will need to install two things:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \texttt{R}, a programming language
\item
  RStudio, a software program that helps you program in \texttt{R}

  \begin{itemize}
  \tightlist
  \item
    This type of software program is called an IDE, an Integrated Development Environment
  \end{itemize}
\end{enumerate}

You don't necessarily need RStudio to program in \texttt{R}, but it makes life much easier and it is what we'll be using throughout the course.

\hypertarget{installing-r}{%
\section{\texorpdfstring{Installing \texttt{R}}{Installing R}}\label{installing-r}}

To install \texttt{R}, go to \url{https://cran.irsn.fr/index.html}, select the appropriate operating system, and follow the instructions.

For example, if you have a Mac, you will click on ``Download R for macOS,'' followed by the ``R-4.3.2-arm64.pkg'' link beneath the ``Latest release'' header.

If you have a PC running Windows, you will click on ``Download R for Windows'' followed by ``install R for the first time'' and ``Download R-4.3.2 for Windows.''

In either case, your browser will start downloading an executable installation file which you will then need to run to install \texttt{R}.

\emph{CAUTION} - A couple of things you may need to watch out for:

\begin{itemize}
\item
  If you are using an older laptop (\textgreater{} 10 years old), you may need to download a different version of \texttt{R} or RStudio. If in doubt, read the instructions on the download page and refer to your operating system version to find the right version.
\item
  If you have very little hard drive space on your computer, you may need to clear some space before you install RStudio. The latest RStudio version requires 215 MB and you will likely need some additional space for other software and data we will be using in the course later on. Around 2 GB should suffice.
\end{itemize}

\hypertarget{installing-rstudio}{%
\section{Installing RStudio}\label{installing-rstudio}}

Once you've installed \texttt{R}, go to \url{https://posit.co/download/rstudio-desktop/}.

Posit (a company formerly known as RStudio) offers RStudio Desktop free of charge. Posit also offers a cloud-hosted version of the software (called Posit Cloud) which has both free and paid tiers. If you have trouble running RStudio Desktop on your computer, you may wish to consider using a Posit Cloud account, as described in the course syllabus.

Step 1 is complete, you've already installed \texttt{R}. On the landing page linked above, you'll find different versions of RStudio according to your computer's operating system. Select the operating system that corresponds to your particular case (Windows, MacOS, or Linux), download the installer, and then run the installation file from your computer and follow the on-screen steps.

If all goes well, your screen should look something like this once you have RStudio correctly installed and running:

\includegraphics{docs/_main_files/figure-html/RStudio clean install.png}

If your screen looks like the image below, it means that you've accidentally opened RGui, a basic graphical user interface included with \texttt{R}, and not RStudio. We're always going to be working in RStudio for this class, so close out of RGui and open RStudio instead.

\includegraphics{docs/_main_files/figure-html/Base R GUI.PNG}

\hypertarget{using-the-console}{%
\section{Using the Console}\label{using-the-console}}

Now the fun begins. The RStudio window you've opened consists of a few different parts. The most important of these right now is the console \href{https://docs.posit.co/ide/user/ide/guide/ui/ui-panes.html}{pane} (highlighted below).

\includegraphics{docs/_main_files/figure-html/RStudio console box.png}

The console allows you to interact with your computer using \texttt{R}. So, for example, if I want to use my computer as an over-sized calculator, I can type in the following \texttt{R} code in the console:

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1}\SpecialCharTok{+}\DecValTok{1}
\end{Highlighting}
\end{Shaded}

What happens when you press \texttt{Enter} on your keyboard? You get something like this:

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1}\SpecialCharTok{+}\DecValTok{1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2
\end{verbatim}

You've provided an \textbf{input}, \texttt{1+1}, and received an \textbf{output}, \texttt{2}. In other words, using the language of \texttt{R}, you've told your computer to add one plus one and your computer has correctly interpreted your command and returned an answer, two. When your computer does not know how to interpret a command, usually because you've made a mistake, you will receive an error message as the output instead. Identifying errors and being able to correct them is an essential skill for a programmer.

One more note about outputs: the first number in brackets next to your output, \texttt{{[}1{]}}, indicates the number of the line of output. This is especially helpful when you are running code that generates multiple lines of output. We will see some examples of this later on.

For now, try entering a few more inputs, such as:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \texttt{10/3}
\item
  \texttt{(10/3)\ +\ 1}
\item
  \texttt{(10/3)\ +\ 1\ +\ (5.111)\textbackslash{}\^{}2}
\end{enumerate}

\texttt{R} is able to handle basic math operations with ease. What about other operations? Can you work with variables in \texttt{R}?

Try typing this in the console:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{=} \DecValTok{1}
\end{Highlighting}
\end{Shaded}

What happens when you press \texttt{Enter}?

\includegraphics{docs/_main_files/figure-html/RStudio console_x1.png}

You may have noticed that there is no output. But, that doesn't mean nothing has happened. In fact, something has happened. You've stored a value, \texttt{1}, in a variable, \texttt{x}, somewhere in your computer's memory or in what we might call the environment. You don't receive an output, but RStudio reminds you of your new variable's existence via the Environment pane in the top right.

We can recall the value we input into our variable, \texttt{x}, by entering the variable name in the console:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1
\end{verbatim}

See! Your computer remembers what you stored in your environment.

Try the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Can you assign a new value to your variable x?
\item
  Can you perform math operations on a variable (e.g., x*2)?
\item
  Can you create a new variable, y, and use it in math operations with x (e.g., x * y)?
\item
  Can you change the type of variable? What if, for example, I don't want x = 1, but I want x equal to the word ``apple''?
\end{enumerate}

\hypertarget{calculations-with-variables}{%
\section{Calculations with Variables}\label{calculations-with-variables}}

If you've made it this far, well done! Here's another thing you can try. Enter the following in the console:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

You'll notice that we're using a different operator here. It's a less than symbol (\textless) followed by a dash (-). This is called an \textbf{assignment operator} and it has the same function as the equals sign (=). You can use either, I just so happen to prefer the way this one looks.

What happens when you press \texttt{Enter}? You have created a \textbf{vector}. Like other types of variables in \texttt{R}, a vector is an \textbf{object}. A vector holds a set of values of the same type. In this case, the object x contains a set of numbers, 1:5.

We can do all sorts of things with vectors and other objects in \texttt{R}. We can, for example, find the sum of a vector.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15
\end{verbatim}

How did we get an output of 15? 1+2+3+4+5 = 15. We can also find the mean of a vector.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3
\end{verbatim}

And, we can perform other fun operations. Try the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Can you find the median of the vector x? What about the mode?\footnote{As you will have found, \texttt{mode()} doesn't calculate a statistic here (although even if it had, you still wouldn't have gotten a meaningful statistic for this particular vector). Some functions are easy to guess, like \texttt{median()} , but others can be false cognates just like in a spoken language. We'll talk more about finding the purpose of a function in the next chapter.}
\item
  What happens when you multiply a vector?
\item
  Can you create a new vector which consists of a set of letters?
\end{enumerate}

\hypertarget{saving-your-work}{%
\section{Saving Your Work}\label{saving-your-work}}

As you've started to see, working with a scripting language like \texttt{R} is quite different from working with software like Microsoft Excel or Google Sheets. You work interactively with data using code rather than by changing values directly in a user interface. No more clicking on cells to change values, now you change them programmatically.

One of the great advantages of interacting with data in this way, particularly for the social sciences, is that it allows us to see all of the steps you've taken to produce your analysis and repeat them. We don't have to take your word for how you've calculated something. We can see it and use it ourselves to produce the same thing.

This means that we leave our source data alone and write the code that produces the analysis. As with any good recipe, we want the code you write to be clear and easy to follow so that we can come back to it and understand what we did. We'll say more about how to do this later on.

There are a couple of different ways of saving your code:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  In an R Script, a simple text file ending in a \texttt{.r} extension
\item
  In an R Markdown file, an interactive format that allows you to see your code and the results together in the same file
\end{enumerate}

We're going to start with an R Script file and try out R Markdown later on.

\hypertarget{creating-and-saving-an-r-script}{%
\section{Creating and Saving an R Script}\label{creating-and-saving-an-r-script}}

To create an R Script file in RStudio, go to File \textgreater{} New File \textgreater{} R Script.

\includegraphics{docs/_main_files/figure-html/RStudio_Opening an R Script File.png}

You should now have a window open in RStudio which looks like this:

\includegraphics{docs/_main_files/figure-html/RStudio_Opened RScript.png}

You can enter comments in your R Script file using a hash tag (\texttt{\#}) at the beginning of each comment line. A hash tag lets \texttt{R} know that this line should not be run as code. Its purpose is to tell us what is happening in a particular section of the code.

I like to start by adding my name, the date, and a description to each file I use. I'll ask that you use a header for each \texttt{R} file you submit for this class as well.

\includegraphics{docs/_main_files/figure-html/RStudio_Commenting in an R Script file.png}

Now, save your R Script somewhere on your computer. Go to File \textgreater{} Save As, then choose a safe place on your computer to store it (I recommend creating a folder for this course), give your file a name, and press save. I called mine ``hello\_world''.

\hypertarget{interacting-in-an-r-script}{%
\section{Interacting in an R Script}\label{interacting-in-an-r-script}}

Interacting in an R Script is slightly different from interacting with the console. Now when you type in code and hit \texttt{Enter}, it will not execute the code, it just creates a new line in your file.

To run code in a script in RStudio, you can either:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Select the lines you wish to run with your cursor and then press \texttt{Ctrl} + \texttt{Enter}
\item
  Or, put your cursor on the line you wish to run and click the \texttt{Run} button in the upper-right of the R Script pane
\end{enumerate}

\includegraphics{docs/_main_files/figure-html/RStudio_Run button.png}

The first option allows you to run multiple lines at a time. The second runs only the line you are currently on. The results of your code will appear in the console pane below your R Script file when run successfully.

After you finish modifying your R Script file, you can save it and close out of RStudio. The next time you wish to access your saved code, you can open your R Script file and it will be exactly as you left it.

\hypertarget{summary}{%
\section{Summary}\label{summary}}

Let's briefly recap what you have learned in this lesson. So far you've learned:

\begin{itemize}
\tightlist
\item
  The difference between \texttt{R} and RStudio
\item
  How to interact with the console
\item
  How to create and store values in variables using an assignment operator
\item
  What a vector is and how to create one
\item
  How to use basic functions like \texttt{sum()} and \texttt{mean()} to perform calculations
\item
  How to make comments using the \texttt{\#} symbol
\item
  How to create and save R Script files
\end{itemize}

\hypertarget{working-with-data-in-r}{%
\chapter{\texorpdfstring{Working with Data in \texttt{R}}{Working with Data in R}}\label{working-with-data-in-r}}

Before we can get to the nitty-gritty of working with real data, we need to familiarize ourselves with a few more essential concepts.

\hypertarget{functions}{%
\section{Functions}\label{functions}}

Last class, we assigned a vector to a variable like this:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my\_vector }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{6}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Where \texttt{my\_vector} is an object and \({1,2,3,4,5,6}\) is the set of values assigned to it. When you run this code in your console (or in a script file), your new variable and its assigned values are stored in short-term memory and appear in the Environment pane of RStudio.

When we assigned a single value to another variable, however, as in:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{\textless{}{-}} \DecValTok{1}
\end{Highlighting}
\end{Shaded}

or,

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{first\_name }\OtherTok{=} \StringTok{\textquotesingle{}Wesley\textquotesingle{}}
\end{Highlighting}
\end{Shaded}

we didn't use \texttt{c()}. So, what exactly is \texttt{c()}?

Like \texttt{sum()} or \texttt{mean()}, \texttt{c()} is a \textbf{function}. Functions play an important role in all programming languages. They are snippets of code, often hidden in the background, that allow us to accomplish specific tasks, like adding up all of the numbers in a vector, taking the mean, or creating a vector. In \texttt{R}, \texttt{c()} is a function which \textbf{\emph{c}}ombines values into a vector or list.

Functions give us the ability to recall previously written code to perform the same task over again. Why re-write code every time you need to use it, after all, when you could use the same code you used last time? Instead of copying and pasting code, we can put it in a function, save it somewhere, and call it when we need it.

\hypertarget{calling-a-function}{%
\subsection{Calling a Function}\label{calling-a-function}}

When we want to use a function, or `call it' as we will sometimes say, we type in the name of the function, enclose \textbf{arguments} in a set of parentheses, and run the command. The general form looks something like this:

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{function}\NormalTok{([arg1], [arg2], ...)}
\end{Highlighting}
\end{Shaded}

\hypertarget{using-arguments-in-a-function}{%
\subsection{Using Arguments in a Function}\label{using-arguments-in-a-function}}

In some cases, you may just have one argument for a function, as when you want to use the \texttt{sum()} function to add the elements of a vector:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(my\_vector)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 21
\end{verbatim}

In other cases, you can have multiple arguments:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(my\_vector, my\_vector)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 42
\end{verbatim}

Arguments can be required or optional and the number of arguments and the order in which they are input depends on the specific function you are using and what you are trying to accomplish. The \texttt{sum()} function, for instance, returns the sum of all values given as arguments.

Arguments can also be used to specify options for a function. Take a look at the example below:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(my\_vector, }\ConstantTok{NA}\NormalTok{, my\_vector)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] NA
\end{verbatim}

Here we are using the \texttt{sum()} function to add \texttt{my\_vector} twice, as in the previous example, but now with a missing value (\texttt{NA}). Because the sum of two vectors plus a missing value is unknown, we get an unknown value (\texttt{NA}) as the output.

If we want the \texttt{sum()} function to ignore the unknown value, we can provide it with an additional, named argument which tells it to ignore \texttt{NA}. We can specify this by adding \texttt{,\ na.rm\ =\ TRUE} to our function call. See what happens below:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(my\_vector, }\ConstantTok{NA}\NormalTok{, my\_vector, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 42
\end{verbatim}

We're back to an answer of 42. The \texttt{sum()} function ignored the missing value, as we specified, and added the two vectors.

All functions have named arguments and an ordering to them. If you omit the name of an argument in your function call, the function processes them according to their default order. It is generally a good habit to specify argument names, as in the example below where the `x' argument takes the object you are trying to sum, but it is not entirely necessary for simple functions.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\AttributeTok{x =}\NormalTok{ my\_vector)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 21
\end{verbatim}

\hypertarget{getting-help-with-functions}{%
\subsection{Getting Help with Functions}\label{getting-help-with-functions}}

As you progress in \texttt{R}, you will learn many different functions and it can be difficult to keep track of all of the different arguments. Whenever you want to know more about what a function does or what arguments it takes, simply type \texttt{?function\_name} into the RStudio console and you will get some useful documentation in the Help pane located in the lower-right of your RStudio window.

\begin{verbatim}
?sum
\end{verbatim}

\includegraphics{docs/_main_files/figure-html/RStudio_Help Pane.PNG}

\hypertarget{check-your-understanding}{%
\subsection*{Check Your Understanding:}\label{check-your-understanding}}
\addcontentsline{toc}{subsection}{Check Your Understanding:}

Let's take a quick pause to make sure we understand what we just learned.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Create a vector of three numbers and assign it to a variable called \texttt{first\_vector}. Now use the \texttt{mean()} function to find the average of \texttt{first\_vector}.
\item
  Using the \texttt{c()} function, create another vector called \texttt{second\_vector} which includes the values of \texttt{first\_vector} and an \texttt{NA} value. Try it on your own first, then click this footnote to see the answer.\footnote{\texttt{second\_vector\ \textless{}-\ c(first\_vector,\ NA)}}
\item
  Using the \texttt{na.rm\ =\ TRUE} argument, calculate the mean of \texttt{second\_vector}.
\end{enumerate}

\hypertarget{packages}{%
\section{Packages}\label{packages}}

One of the great benefits of \texttt{R} is its power and flexibility. We've seen how functions provide us with the ability to reuse code, but functions are common to any programming language or statistical software.

It may sound cliché, but what makes \texttt{R} special is its community. \texttt{R} is a free and open-source software, which means that anyone can use or contribute to it. If you develop a new statistical method, for instance, you can write the code necessary to implement it and share it with others.

Base \texttt{R}, which you installed last class, comes with a number of built-in functions like \texttt{mean()}, \texttt{sum()}, \texttt{range()}, and \texttt{var()} . But, \texttt{R} users working out of the goodness of their hearts have developed many other functions that accomplish an array of tasks, from making aesthetically-pleasing visualizations to executing complex machine learning algorithms.

These functions are put together into what are called \textbf{packages}, which can be easily installed and loaded into \texttt{R}. Packages can also contain data and other compiled code.

\hypertarget{installing-packages}{%
\subsection{Installing Packages}\label{installing-packages}}

We're going to use the \texttt{install.packages()} function to install one such package, called \textbf{tidyverse}.

\begin{verbatim}
install.packages('tidyverse')
\end{verbatim}

Once you've run this command in your RStudio console, you will have downloaded the tidyverse and saved it to your \textbf{library}. The library is simply where your packages are stored.

\href{https://tidyverse.tidyverse.org/}{Tidyverse} is actually a set of packages, including \texttt{dplyr} and \texttt{ggplot2}, all of which are useful for data analysis in \texttt{R}. We'll be using the tidyverse throughout this course and you will find that it's the most commonly used set of packages for data analysis in \texttt{R}.

\hypertarget{loading-libraries}{%
\subsection{Loading Libraries}\label{loading-libraries}}

Whenever you start an \texttt{R} session and want to use a package, you have to be sure to load it. Loading a package makes sure that your computer knows what functions and data are inside, so that you can call them at will.

To load an \texttt{R} package, you can use the \texttt{library()} function, like this:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.1.4     v readr     2.1.5
## v forcats   1.0.0     v stringr   1.5.1
## v ggplot2   3.4.4     v tibble    3.2.1
## v lubridate 1.9.3     v tidyr     1.3.1
## v purrr     1.0.2     
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

Now, that you've loaded tidyverse, you can access it's special functions like \texttt{mutate()} or its data sets, like \texttt{starwars}. Try entering \texttt{starwars} in your console after you've loaded the tidyverse. What's inside?

\hypertarget{loading-data}{%
\section{Loading Data}\label{loading-data}}

Great, you know what a function is, you have the tidyverse installed, and you've seen that data can be contained in packages, which are easy to install and load.

\hypertarget{using-data-from-packages}{%
\subsection{Using Data from Packages}\label{using-data-from-packages}}

Let's install and load another package, so that we can take a look at some more data.

\begin{verbatim}
install.packages('socviz')
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(socviz)}
\end{Highlighting}
\end{Shaded}

The \texttt{socviz} package accompanies a textbook called \textbf{\emph{Data Visualization}} written by Kieran Healy, a Professor of Sociology at Duke University, and it contains some interesting datasets including election data from the 2016 U.S. presidential election. This dataset is stored in an object titled \texttt{election}. Once you have \texttt{socviz} installed and loaded, you can get a preview of its contents by entering the name of the object:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{election}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 51 x 22
##    state     st     fips total_vote vote_margin winner party pct_margin r_points
##    <chr>     <chr> <dbl>      <dbl>       <dbl> <chr>  <chr>      <dbl>    <dbl>
##  1 Alabama   AL        1    2123372      588708 Trump  Repu~     0.277     27.7 
##  2 Alaska    AK        2     318608       46933 Trump  Repu~     0.147     14.7 
##  3 Arizona   AZ        4    2604657       91234 Trump  Repu~     0.035      3.5 
##  4 Arkansas  AR        5    1130635      304378 Trump  Repu~     0.269     26.9 
##  5 Californ~ CA        6   14237893     4269978 Clint~ Demo~     0.300    -30.0 
##  6 Colorado  CO        8    2780247      136386 Clint~ Demo~     0.0491    -4.91
##  7 Connecti~ CT        9    1644920      224357 Clint~ Demo~     0.136    -13.6 
##  8 Delaware  DE       10     443814       50476 Clint~ Demo~     0.114    -11.4 
##  9 District~ DC       11     311268      270107 Clint~ Demo~     0.868    -86.8 
## 10 Florida   FL       12    9502747      112911 Trump  Repu~     0.0119     1.19
## # i 41 more rows
## # i 13 more variables: d_points <dbl>, pct_clinton <dbl>, pct_trump <dbl>,
## #   pct_johnson <dbl>, pct_other <dbl>, clinton_vote <dbl>, trump_vote <dbl>,
## #   johnson_vote <dbl>, other_vote <dbl>, ev_dem <dbl>, ev_rep <dbl>,
## #   ev_oth <dbl>, census <chr>
\end{verbatim}

For ease of use, we're going to store a copy of this data in a new object in our environment called \texttt{election\_2016}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{election\_2016 }\OtherTok{\textless{}{-}}\NormalTok{ election}
\end{Highlighting}
\end{Shaded}

Now, we can play around with it. In addition to getting a preview of the data by entering the name of our object in the console, we can also access it through the Environment pane of our RStudio window. Click on \texttt{election\_2016} and you will see the full dataset.

Just like in a spreadsheet, you can scroll through the full set of columns and rows. Remember, of course, that you cannot edit values in this view tab. This is by design. If we want to make changes to the data or perform calculations, we need to do so programmatically.

\hypertarget{data-types-and-data-structures}{%
\section{Data Types and Data Structures}\label{data-types-and-data-structures}}

This seems about as good a point as any to talk about the different types of data you will be working with in R.

\hypertarget{data-types}{%
\subsection{Data Types}\label{data-types}}

There are six different basic data types in \texttt{R}. The most important for our purposes are:

\begin{itemize}
\tightlist
\item
  \textbf{character}: letters such as `a' or sets of letters such as `apple'
\item
  \textbf{numeric}: numbers such as 1, 1.1 or 23
\item
  \textbf{logical}: the boolean values, TRUE and FALSE
\end{itemize}

The other types are integers (which can only hold integers and take the form \texttt{1L}), complex (as in complex numbers with an imaginary component, 1+2i), and raw (raw data in the form of bytes). You have already used the previous three and we will never use the latter three.

If you wish to check the data type of an object, you can use the \texttt{class()} function.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{class}\NormalTok{(my\_vector)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "numeric"
\end{verbatim}

\hypertarget{data-structures}{%
\subsection{Data Structures}\label{data-structures}}

There are many different data structures in \texttt{R}. You've already become familiar with one, vectors, a set of values of the same type. Other types of data structures include:

\begin{itemize}
\tightlist
\item
  \textbf{list}: a set of values of different types
\item
  \textbf{factor:} an ordered set of values, often used to define categories in categorical variables
\item
  \textbf{data frame}: a two-dimensional table consisting of rows and columns similar to a spreadsheet
\item
  \textbf{tibble:} a special version of a data frame from the \emph{tidyverse}, intended to keep your data nice and tidy
\end{itemize}

Note that data structures are usually subsettable, which means that you can access elements of them. Observe:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my\_list }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}a\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}b\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}c\textquotesingle{}}\NormalTok{, }\DecValTok{2}\NormalTok{)}
\NormalTok{my\_list[}\DecValTok{2}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "b"
\end{verbatim}

In the example above, we've called an element of the list, \texttt{my\_list}, using an index number in a set of brackets. Since we entered the index, \texttt{2}, inside brackets next to our list name, we received the second element of the list, the character \texttt{b}. We can also modify elements of a list in the same way.

Let's say that I now want to change `b', the second element of \texttt{my\_list}, to the word `blueberry':

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my\_list[}\DecValTok{2}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{\textquotesingle{}blueberry\textquotesingle{}}
\NormalTok{my\_list}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "a"         "blueberry" "c"         "2"
\end{verbatim}

Easy enough. Now try it out yourself:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Create a vector with three elements: ``sociology'', ``economics'', and ``psychology''
\item
  Call each of them individually.
\item
  Change the value of the second element to the value of the first element.
\item
  Change the value of the third element to the value of the first element.
\end{enumerate}

Be sure to do the last two programmatically rather than by re-typing the initial values.

\hypertarget{using-functions-with-data}{%
\section{Using Functions with Data}\label{using-functions-with-data}}

Back to the elections data. We have our 2016 U.S. Presidential Election data stored in a \textbf{tibble} called \texttt{election\_2016}.

If I want to output a single column from the data, I can do so by typing in the name of the data followed by the \texttt{\$} symbol, also known as the \textbf{subset operator}, and the name of the column.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{election\_2016}\SpecialCharTok{$}\NormalTok{state}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "Alabama"              "Alaska"               "Arizona"             
##  [4] "Arkansas"             "California"           "Colorado"            
##  [7] "Connecticut"          "Delaware"             "District of Columbia"
## [10] "Florida"              "Georgia"              "Hawaii"              
## [13] "Idaho"                "Illinois"             "Indiana"             
## [16] "Iowa"                 "Kansas"               "Kentucky"            
## [19] "Louisiana"            "Maine"                "Maryland"            
## [22] "Massachusetts"        "Michigan"             "Minnesota"           
## [25] "Mississippi"          "Missouri"             "Montana"             
## [28] "Nebraska"             "Nevada"               "New Hampshire"       
## [31] "New Jersey"           "New Mexico"           "New York"            
## [34] "North Carolina"       "North Dakota"         "Ohio"                
## [37] "Oklahoma"             "Oregon"               "Pennsylvania"        
## [40] "Rhode Island"         "South Carolina"       "South Dakota"        
## [43] "Tennessee"            "Texas"                "Utah"                
## [46] "Vermont"              "Virginia"             "Washington"          
## [49] "West Virginia"        "Wisconsin"            "Wyoming"
\end{verbatim}

If I want to perform a calculation on a column, I can pass the column as an argument to a function like so:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Sum the total number of votes cast in the 2016 Presidential election.}
\FunctionTok{sum}\NormalTok{(election\_2016}\SpecialCharTok{$}\NormalTok{total\_vote, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 137125484
\end{verbatim}

The \texttt{na.rm} argument isn't strictly necessary in this case (since there are no missing or unknown values), but it's good to remember that it's there when you need it.

For the remainder of today's session, I'd like you play around with this data. In particular:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Identify the variable type for the \texttt{ST}, \texttt{pct\_johnson}, and \texttt{winner} columns.
\item
  Calculate the mean \texttt{vote\_margin} across the states.
\item
  Use the \texttt{table()} function to count the number of states won by each presidential candidate.
\item
  Create a variable which contains the total number of votes received by Hillary Clinton (contained in the column \texttt{clinton\_vote}) and a variable containing the total number of votes received by Donald Trump (\texttt{trump\_vote}). Take the difference of the two.
\item
  Create a variable containing the total number of electoral votes received by Hillary Clinton (contained in \texttt{ev\_dem}) and another containing the total number received by Donald Trump (\texttt{ev\_rep}). Take the difference of the two.
\item
  Try using the \texttt{plot(x=,\ y=)} function to plot a couple of numeric columns.
\end{enumerate}

\hypertarget{homework-1}{%
\chapter*{Homework 1}\label{homework-1}}
\addcontentsline{toc}{chapter}{Homework 1}

\textbf{Due Date:} Tuesday, 13 February by 23:59:59

\textbf{Submission Instructions:} Submit your completed R script file to Moodle.

This homework will be relatively short and straight-forward. The goal is to ease you into \texttt{R} now so that you are ready to complete some of the more complex data analysis that will take place later.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Create an \texttt{R} script and save it with an appropriate name. Add a header to your R script file in the format below.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Name: [first\_name] [last\_name]}
\CommentTok{\# Date: [date]}
\CommentTok{\# Description: [brief description of the file] }

\CommentTok{\# Question 2:}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\item
  In your \texttt{R} script file, load the \texttt{tidyverse} package.
\item
  Create a vector with the following set of numbers: \({30, 60, 90, 120, 150}\).

  \begin{enumerate}
  \def\labelenumii{\alph{enumii}.}
  \item
    Multiply the vector by 2. In a brief comment, tell me what the result was.
  \item
    Take the vector and divide it by 3. Tell me what the result was in a brief comment.
  \item
    Multiply the vector by itself. Tell me what the result was in a brief comment.
  \item
    Return the third element of the vector.
  \item
    Replace the second element of the vector with a missing value (\texttt{NA}).
  \item
    Sum the vector, excluding the missing value. In a comment, write the answer.
  \end{enumerate}
\item
  Using the \texttt{socviz} package (see section 2.3 of the course textbook), load the \texttt{election} dataset into a new object called \texttt{elec}.
\end{enumerate}

~ a. Find the total popular vote received by Gary Johnson using the \texttt{johnson\_vote} variable.

~ b. Find the total popular vote received by `Other' candidates using the \texttt{other\_vote} variable.

~ c.~In a comment answer the following question: who received more votes, Gary Johnson or ``other'' candidates? By how much?

~ d.~Use the \texttt{sum()} function on the \texttt{state} variable. In a brief comment, explain why this didn't work and what the error message is telling you.

\hypertarget{summarizing-data-with-dplyr}{%
\chapter{\texorpdfstring{Summarizing Data with \texttt{dplyr}}{Summarizing Data with dplyr}}\label{summarizing-data-with-dplyr}}

In the previous chapter, you learned how to load data from a package, how to access a column from a tibble using the subset operator \texttt{\$}, and how to use basic functions to answer questions like: what was the total number of votes cast in the 2016 U.S. presidential election?

We've had a couple strokes of luck so far. Our data has been nice and tidy and our questions haven't really required us to poke around in our data to find the answers we are interested in. This brings us to \emph{data wrangling} - the art and science of manipulating, distilling, or cajoling data into a format that allows you to find the answers you are seeking.\footnote{Data wrangling, if it can be defined, is as an expansive topic. We'll focus on summarizing data today.}

For this lesson, we are going to continue to maintain the illusion of neat and tidy data and focus on learning the tools necessary to dig deeper into a data set: in particular, \texttt{dplyr} and the \textbf{pipe operator}. In the next lesson, our luck will run out and we will be confronted with the harsh reality of unseemly data.\footnote{Sadly, almost all data you encounter out in the wild will be very unseemly for one reason or another. But, maybe after taking this course and ascending the ranks of government/business/academia, you too will become an evangelical for orderly data and help bring peace to a world of mismanaged data.}

\hypertarget{basic-description-with-base-r}{%
\section{\texorpdfstring{Basic Description with Base \texttt{R}}{Basic Description with Base R}}\label{basic-description-with-base-r}}

Let's use an example to get started. Last class, you toyed around with the 2016 U.S. presidential election data from the \texttt{socviz} package, a helpful collection of data sets and other goodies developed by Kieran Healy.\footnote{The \texttt{socviz} package serves as an accompaniment to Healy's textbook, \emph{Data Visualization}, which is highly recommended.}

We'll use another data set from the same package in a moment, but, for now, let's return to the \texttt{election} data. We're also going to re-load our new best friend, \emph{tidyverse}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(socviz)}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

Libraries loaded. Remember, once you have the packages installed, you don't need to do it again. So, don't include \texttt{install.packages()} in your scripts going forward.\footnote{Anytime you do install packages, do it directly in the console. If someone needs to run your code, they should see the \texttt{library()} calls in the beginning of your code (after your header) and will know whether they need to install additional packages or not.

  Alternatively, instead of using the \texttt{library()} function, you can always use the \texttt{require()} function, which has the benefit of both loading packages if you do have them and installing them if you don't.}

We'll load the data into an object in our environment. This time, I'm going to use a shorter name for the tibble to spare myself future pain. Longer names means more to retype later.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{elec\_2016 }\OtherTok{\textless{}{-}}\NormalTok{ election}
\end{Highlighting}
\end{Shaded}

Just like last time, we can do basic calculations on columns. We can even throw in a few new functions for good measure:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# table() gives a contingency table for character variables.}
\CommentTok{\# Here it\textquotesingle{}s the number of states (plus D.C.) won by each candidate.}
\FunctionTok{table}\NormalTok{(elec\_2016}\SpecialCharTok{$}\NormalTok{winner)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Clinton   Trump 
##      21      30
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Wrapping prop.table() around a contingency table gives relative frequencies.}
\CommentTok{\# i.e., Hillary Clinton won 41.2\% of states (plus Washington D.C.) or 21/51.}
\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{table}\NormalTok{(elec\_2016}\SpecialCharTok{$}\NormalTok{winner))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   Clinton     Trump 
## 0.4117647 0.5882353
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# summary() gives us a nice 5{-}number summary for numeric variables.}
\CommentTok{\# Here we see the min, max, median, mean, and quartiles for the pop. vote margin.}
\FunctionTok{summary}\NormalTok{(elec\_2016}\SpecialCharTok{$}\NormalTok{vote\_margin)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    2736   96382  212030  383997  522207 4269978
\end{verbatim}

But, what if I want to do something more specific?

What if I really want to know how much of the popular vote third party Libertarian candidate Gary Johnson won across the different regions of the United States? Here we need special functions from dplyr and the pipe operator.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# An illustrative example {-} no need to try this just yet}
\NormalTok{elec\_2016 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(census) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{total =} \FunctionTok{sum}\NormalTok{(johnson\_vote))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 2
##   census      total
##   <chr>       <dbl>
## 1 Midwest   1203062
## 2 Northeast  676192
## 3 South     1370056
## 4 West      1239925
\end{verbatim}

We'll learn how to do this and more in a moment.

\includegraphics[width=1.55208in,height=\textheight]{docs/_main_files/figure-html/ceci_pipe.png}

\hypertarget{the-pipe-operator}{%
\section{The Pipe Operator}\label{the-pipe-operator}}

The \textbf{pipe operator} is a handy tool indeed. It is a specialized operator that comes from the \texttt{maggritr} package, which itself is contained in the tidyverse.

It looks like this: \texttt{\%\textgreater{}\%}. But, it can also look like this: \texttt{\textbar{}\textgreater{}}.

There isn't much of a difference between the two, so you can use whichever you prefer as long as you are consistent.\footnote{See here for more on the differences: \href{https://www.tidyverse.org/blog/2023/04/base-vs-magrittr-pipe/\#}{https://www.tidyverse.org/blog/2023/04/base-vs-magrittr-pipe}}

The pipe operator has a straightforward function: it allows you to combine a series of steps into a single command. And, it does this in a way that makes your code legible. Whenever you see the pipe operator, you should read it as though it is saying, ``And then {[}do this{]}.''

So in the previous example I gave, you might read it as:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{elec\_2016 }\SpecialCharTok{\%\textgreater{}\%}                            \CommentTok{\# Take the election data AND THEN}
  \FunctionTok{group\_by}\NormalTok{(census) }\SpecialCharTok{\%\textgreater{}\%}                   \CommentTok{\# group it by census region AND THEN}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{total =} \FunctionTok{sum}\NormalTok{(johnson\_vote))   }\CommentTok{\# sum up the Johnson vote.}
\end{Highlighting}
\end{Shaded}

Note a couple of things here:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The pipe operator always goes at the end of each line, followed by a new line
\item
  The pipe operator never goes at the end of the command
\end{enumerate}

The first is a convention to make code more readable and the second is a requirement. If you leave a pipe operator at the end of your statement, \texttt{R} will search for the missing code and then give you an unhappy error when you try to run more code. Don't leave a pipe operator hanging.

\hypertarget{functions-from-dplyr}{%
\section{\texorpdfstring{Functions from \texttt{dplyr}}{Functions from dplyr}}\label{functions-from-dplyr}}

\texttt{dplyr} (pronounced dee-ply-R) is a set of tools for working with tabular data. It's one of the packages in tidyverse (along with \texttt{ggplot2}, \texttt{tidyr}, \texttt{tibble}, \texttt{readr}, and a few others), so you don't have to load it separately.

\texttt{dplyr} has a handful of special functions:

\begin{itemize}
\item
  \texttt{group\_by()}, which groups data together at the level we desire (such as states by census region).
\item
  \texttt{filter()}, which gives us the rows corresponding to criteria entered as an argument
\item
  \texttt{select()}, which selects columns from the original data
\item
  \texttt{summarize()} or \texttt{summarise()}, which performs calculations\footnote{It's the same function, but two different spellings depending on who you've learned English from.}
\item
  \texttt{mutate()}, which creates new columns (or variables)
\item
  \texttt{arrange()}, which sorts the row order by column values
\end{itemize}

\hypertarget{glimpsing-gss-data}{%
\section{Glimpsing GSS Data}\label{glimpsing-gss-data}}

Let's load another data set from \texttt{socviz}. This one is called \texttt{gss\_sm} and contains a nice, clean extract from the 2016 General Social Survey.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gss }\OtherTok{\textless{}{-}}\NormalTok{ gss\_sm}
\end{Highlighting}
\end{Shaded}

The \href{https://gss.norc.org/}{General Social Survey} is a nationally representative biennial survey of U.S. adults on sociological topics produced by the National Opinion Research Center (NORC) at the University of Chicago since 1972.

Take a quick look at the data. You can use \texttt{glimpse()}, another \texttt{dplyr} function, to get a sense of what's inside and you can look at it visually using \texttt{view()}. Typing in \texttt{?gss\_sm} (the original name of the data set from the package) will tell you what the variables are.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{view}\NormalTok{(gss)}
\FunctionTok{glimpse}\NormalTok{(gss)}
\end{Highlighting}
\end{Shaded}

There's a wealth of data in here. You might also notice that the data is at the \emph{individual-level}. In this data, each row represents an individual respondent and each column is a variable (or a coded response to a survey question).

\hypertarget{selecting-columns}{%
\section{Selecting Columns}\label{selecting-columns}}

Maybe we want to narrow in and look at just a few variables. We can use the \texttt{select()} function to do this.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gss }\SpecialCharTok{\%\textgreater{}\%}                             \CommentTok{\# Take the GSS data AND THEN}
  \FunctionTok{select}\NormalTok{(id, sex, religion)         }\CommentTok{\# take just the ID, sex, and religion columns.}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2,867 x 3
##       id sex    religion  
##    <dbl> <fct>  <fct>     
##  1     1 Male   None      
##  2     2 Male   None      
##  3     3 Male   Catholic  
##  4     4 Female Catholic  
##  5     5 Female None      
##  6     6 Female None      
##  7     7 Male   None      
##  8     8 Female Catholic  
##  9     9 Male   Protestant
## 10    10 Male   None      
## # i 2,857 more rows
\end{verbatim}

The select function returned a tibble with just the three variables I wanted to look at. I can always save a copy of this output by storing it in a new object:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gender\_relig }\OtherTok{\textless{}{-}}\NormalTok{ gss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(id, sex, religion)}
\end{Highlighting}
\end{Shaded}

And, if I take a look at it and then decide I don't want this copy, I can always get rid of it using the \texttt{rm()} function.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{view}\NormalTok{(gender\_relig)}
\FunctionTok{rm}\NormalTok{(gender\_relig)}
\end{Highlighting}
\end{Shaded}

\hypertarget{grouping-and-summarizing}{%
\section{Grouping and Summarizing}\label{grouping-and-summarizing}}

Let's say we want to summarize the respondents by religious affiliation.

To do this, we first have to tell the computer how we are going to group the data. Grouping doesn't change the data, but it prepares \texttt{R} to interpret it according to the groups we specify. We're going to group by the \texttt{religion} variable.

Next, we have to tell the computer how to \texttt{summarize()} the groups. We're going to count the respondents using \texttt{n()}. \texttt{n()} just counts the rows within each group.\footnote{There are other options for this, like \texttt{count()} or \texttt{tally()} , but I won't use them here.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(religion) }\SpecialCharTok{\%\textgreater{}\%}      \CommentTok{\# Group by religion}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{())      }\CommentTok{\# Create a total by counting the rows}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   religion   total
##   <fct>      <int>
## 1 Protestant  1371
## 2 Catholic     649
## 3 Jewish        51
## 4 None         619
## 5 Other        159
## 6 <NA>          18
\end{verbatim}

As you can see, \texttt{summarize()} needs you to provide a new column name and a measurement. In the example above, we named the new column \texttt{total} and asked it to count the total number of respondents by group using the \texttt{n()} function.

Again, if we wanted to, we could save a copy of this summary in a new tibble, as in the command below. Our original table will always be untouched unless we intentionally save over it (e.g., \texttt{gss\ \textless{}-\ gss\ \%\textgreater{}\%\ ...}).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{relig }\OtherTok{\textless{}{-}}\NormalTok{ gss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(religion) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

We can also group by two columns, such that we can find religious affiliation by sex, for example:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(religion, sex) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'religion'. You can override using the
## `.groups` argument.
\end{verbatim}

\begin{verbatim}
## # A tibble: 12 x 3
## # Groups:   religion [6]
##    religion   sex    total
##    <fct>      <fct>  <int>
##  1 Protestant Male     559
##  2 Protestant Female   812
##  3 Catholic   Male     287
##  4 Catholic   Female   362
##  5 Jewish     Male      22
##  6 Jewish     Female    29
##  7 None       Male     339
##  8 None       Female   280
##  9 Other      Male      58
## 10 Other      Female   101
## 11 <NA>       Male      11
## 12 <NA>       Female     7
\end{verbatim}

Now we can see the number of protestants who are male and the number who are female.

The ordering of the groups matters somewhat. Because religion came first in our \texttt{group()} function, our results show us the number of protestants who are male and the number of protestants who are female.

For a count, this is the same thing as the inverse (e.g., the number of protestants who are male is the same as the number of males who are protestant), but for frequencies this is not the case and the order does matter. You'll get a sense for this in a moment.

\hypertarget{calculating-with-mutate}{%
\section{\texorpdfstring{Calculating with \texttt{mutate()}}{Calculating with mutate()}}\label{calculating-with-mutate}}

Let's add a frequency column and a percentage column so that we can see whether there are gender differences within religious affiliations.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(religion, sex) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{freq =}\NormalTok{ total }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total),}
         \AttributeTok{pct =} \FunctionTok{round}\NormalTok{((freq}\SpecialCharTok{*}\DecValTok{100}\NormalTok{), }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'religion'. You can override using the
## `.groups` argument.
\end{verbatim}

\begin{verbatim}
## # A tibble: 12 x 5
## # Groups:   religion [6]
##    religion   sex    total  freq   pct
##    <fct>      <fct>  <int> <dbl> <dbl>
##  1 Protestant Male     559 0.408  40.8
##  2 Protestant Female   812 0.592  59.2
##  3 Catholic   Male     287 0.442  44.2
##  4 Catholic   Female   362 0.558  55.8
##  5 Jewish     Male      22 0.431  43.1
##  6 Jewish     Female    29 0.569  56.9
##  7 None       Male     339 0.548  54.8
##  8 None       Female   280 0.452  45.2
##  9 Other      Male      58 0.365  36.5
## 10 Other      Female   101 0.635  63.5
## 11 <NA>       Male      11 0.611  61.1
## 12 <NA>       Female     7 0.389  38.9
\end{verbatim}

Notice, we used the same code as before, but we added a \texttt{mutate()} function to create two new columns, \texttt{freq} and \texttt{pct}.

We also told the \texttt{mutate()} function how to calculate the columns. \texttt{freq}, we said, should be the respondents in each group divided by the sum of the groups (or \texttt{freq\ =\ total\ /\ sum(total)}). \texttt{pct} should be the frequency multiplied by 100 and then rounded to the first decimal place, using the \texttt{round()} function. In doing so, we find that among Protestant respondents, 40.8\% are male and 59.2\% are female.

Calculating relative frequencies can be a bit of a beast, but the general form is always the same, so you'll be able to re-use code often.

\hypertarget{how-r-reads-functions}{%
\section{\texorpdfstring{How \texttt{R} Reads Functions}{How R Reads Functions}}\label{how-r-reads-functions}}

You have just seen a bunch of nested functions, which is when a functions is used as an argument inside another functions. It's worth pausing for a second to mention how \texttt{R} reads code, since you will be using this often.

Functions are always read inside out, so a nested function will always evaluate the inner-most function first. Pipe operations, on the other hand, are read from left-to-right (or top-to-bottom, if you're breaking up your code using new lines). The two commands below evaluate in the same way, but \texttt{R} reads them in a slightly different ordering.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Inside{-}out evaluation}
\FunctionTok{sum}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{))               }\CommentTok{\# A vector is created first, then summed.}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Left{-}to{-}right (sequential) evaluation}
\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}                \CommentTok{\# A vector is created AND THEN}
  \FunctionTok{sum}\NormalTok{()                     }\CommentTok{\# it is summed}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6
\end{verbatim}

\hypertarget{filtering}{%
\section{Filtering}\label{filtering}}

Back to the data. What if we only wish to see the Protestant results of our last query? We can add a \texttt{filter()} function.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(religion, sex) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{freq =}\NormalTok{ total }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total),}
         \AttributeTok{pct =} \FunctionTok{round}\NormalTok{((freq}\SpecialCharTok{*}\DecValTok{100}\NormalTok{), }\DecValTok{1}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(religion }\SpecialCharTok{==} \StringTok{"Protestant"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'religion'. You can override using the
## `.groups` argument.
\end{verbatim}

\begin{verbatim}
## # A tibble: 2 x 5
## # Groups:   religion [1]
##   religion   sex    total  freq   pct
##   <fct>      <fct>  <int> <dbl> <dbl>
## 1 Protestant Male     559 0.408  40.8
## 2 Protestant Female   812 0.592  59.2
\end{verbatim}

Usually, you'll want to use the \texttt{filter()} function at the beginning of your query.

Here's another example using \texttt{filter()}. This time, I'm only interested in religious affiliation among holders of graduate degrees.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(degree }\SpecialCharTok{==} \StringTok{\textquotesingle{}Graduate\textquotesingle{}}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(religion) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{freq =}\NormalTok{ total }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total),}
         \AttributeTok{pct =} \FunctionTok{round}\NormalTok{((freq}\SpecialCharTok{*}\DecValTok{100}\NormalTok{), }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 4
##   religion   total    freq   pct
##   <fct>      <int>   <dbl> <dbl>
## 1 Protestant   126 0.396    39.6
## 2 Catholic      63 0.198    19.8
## 3 Jewish        15 0.0472    4.7
## 4 None          82 0.258    25.8
## 5 Other         31 0.0975    9.7
## 6 <NA>           1 0.00314   0.3
\end{verbatim}

Now, we see that 39.6\% of graduate-degree holding respondents were protestant and 25.8\% had no religious affiliation. Later on, we'll learn how to turn this sort of thing into a graph.

\hypertarget{conditional-filtering}{%
\section{Conditional Filtering}\label{conditional-filtering}}

What if we want to filter our respondents for multiple degree types? We want to see, for example, people who have a bachelor's degree \textbf{or} a graduate degree.

For these types of queries, we can use logical operators in our \texttt{filter()} criteria. Here, specifically, we'll use \texttt{\textbar{}} which stands for `\textbf{or}'.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(degree }\SpecialCharTok{==} \StringTok{\textquotesingle{}Graduate\textquotesingle{}} \SpecialCharTok{|}\NormalTok{ degree }\SpecialCharTok{==} \StringTok{\textquotesingle{}Bachelor\textquotesingle{}}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(religion) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{freq =}\NormalTok{ total }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total),}
         \AttributeTok{pct =} \FunctionTok{round}\NormalTok{((freq}\SpecialCharTok{*}\DecValTok{100}\NormalTok{), }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 4
##   religion   total    freq   pct
##   <fct>      <int>   <dbl> <dbl>
## 1 Protestant   367 0.430    43  
## 2 Catholic     193 0.226    22.6
## 3 Jewish        27 0.0316    3.2
## 4 None         204 0.239    23.9
## 5 Other         59 0.0691    6.9
## 6 <NA>           4 0.00468   0.5
\end{verbatim}

Now our results include college graduates and graduate degree holders. If we want to see them broken out separately, all we need to do is change \texttt{group\_by(religion)} to \texttt{group\_by(religion,\ degree)}.

What if we want to filter our observations for all individuals with less than a bachelor's degree?

We can create a vector with our specific criteria and then use it in the filter. Check this out:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{filter\_criteria }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Lt High School\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}High School\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Junior College\textquotesingle{}}\NormalTok{)}

\NormalTok{gss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(degree }\SpecialCharTok{\%in\%}\NormalTok{ filter\_criteria) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(religion, degree) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{freq =}\NormalTok{ total }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total),}
         \AttributeTok{pct =} \FunctionTok{round}\NormalTok{((freq}\SpecialCharTok{*}\DecValTok{100}\NormalTok{), }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'religion'. You can override using the
## `.groups` argument.
\end{verbatim}

\begin{verbatim}
## # A tibble: 17 x 5
## # Groups:   religion [6]
##    religion   degree         total   freq   pct
##    <fct>      <fct>          <int>  <dbl> <dbl>
##  1 Protestant Lt High School   155 0.155   15.5
##  2 Protestant High School      742 0.740   74  
##  3 Protestant Junior College   106 0.106   10.6
##  4 Catholic   Lt High School   100 0.220   22  
##  5 Catholic   High School      322 0.708   70.8
##  6 Catholic   Junior College    33 0.0725   7.3
##  7 Jewish     Lt High School     1 0.0417   4.2
##  8 Jewish     High School       17 0.708   70.8
##  9 Jewish     Junior College     6 0.25    25  
## 10 None       Lt High School    62 0.150   15  
## 11 None       High School      298 0.722   72.2
## 12 None       Junior College    53 0.128   12.8
## 13 Other      Lt High School    10 0.1     10  
## 14 Other      High School       73 0.73    73  
## 15 Other      Junior College    17 0.17    17  
## 16 <NA>       High School        9 0.9     90  
## 17 <NA>       Junior College     1 0.1     10
\end{verbatim}

We've first created a vector, called \texttt{filter\_criteria}, with all of the degree-levels we want to include in our data (we've left out `Graduate' and `Bachelor'). Then, we've changed the filter criteria to say, ``Take all respondents who have a degree listed in our vector, \texttt{filter\ \_criteria}.'' In code, we write this as: \texttt{filter(degree\ \%in\%\ filter\_criteria)}.

\hypertarget{the-in-operator}{%
\subsection{\texorpdfstring{The \texttt{\%in\%} Operator}{The \%in\% Operator}}\label{the-in-operator}}

\texttt{\%in\%} is a special logical operator that checks to see whether the values you are specifying are contained in an object. If the value is contained in the object, your computer will return \texttt{TRUE} and if not, it will return \texttt{FALSE}. This is especially useful for \texttt{filter()} since \texttt{filter()} selects rows based on whether they meet a criteria (\texttt{TRUE}) or not (\texttt{FALSE}).

Here's a simple example of how this operator works in general:

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1} \SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{6} \SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] FALSE
\end{verbatim}

\hypertarget{fancy-tables-with-kable}{%
\section{\texorpdfstring{Fancy Tables with \texttt{kable()}}{Fancy Tables with kable()}}\label{fancy-tables-with-kable}}

If we want to make a table look a little bit nicer, we can add the \texttt{knitr::kable()} function to the end of our query to produce a more polished looking table.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(degree }\SpecialCharTok{==} \StringTok{\textquotesingle{}Graduate\textquotesingle{}}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(religion) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{freq =}\NormalTok{ total }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total),}
         \AttributeTok{pct =} \FunctionTok{round}\NormalTok{((freq}\SpecialCharTok{*}\DecValTok{100}\NormalTok{), }\DecValTok{1}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|r|r|r}
\hline
religion & total & freq & pct\\
\hline
Protestant & 126 & 0.3962264 & 39.6\\
\hline
Catholic & 63 & 0.1981132 & 19.8\\
\hline
Jewish & 15 & 0.0471698 & 4.7\\
\hline
None & 82 & 0.2578616 & 25.8\\
\hline
Other & 31 & 0.0974843 & 9.7\\
\hline
NA & 1 & 0.0031447 & 0.3\\
\hline
\end{tabular}

The \texttt{::} operator here is just used to tell the computer to pull the \texttt{kable()} function from the \texttt{knitr} package (a member of the \texttt{tidyverse)}. This is useful when there are multiple functions with the same name in different packages.

You can also add additional code to your \texttt{kable()} function to customize the look of your table (see \href{https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html}{here} for examples).

\hypertarget{another-example}{%
\section{Another Example}\label{another-example}}

What if I want to do something crazy like find all survey respondents who are Protestant or Catholic, voted for Obama in the 2012 U.S. Presidential election, and have children? And, I'd like to know their breakdown by relative frequency across regions of the U.S. Here's a brief example:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(religion }\SpecialCharTok{==} \StringTok{"Protestant"} \SpecialCharTok{|}\NormalTok{ religion }\SpecialCharTok{==} \StringTok{"Catholic"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(obama }\SpecialCharTok{==} \DecValTok{1}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(childs }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(region) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{total =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{freq =} \FunctionTok{round}\NormalTok{(total }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total),}\DecValTok{4}\NormalTok{),}
         \AttributeTok{pct =} \FunctionTok{round}\NormalTok{((freq}\SpecialCharTok{*}\DecValTok{100}\NormalTok{), }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 9 x 4
##   region          total   freq   pct
##   <fct>           <int>  <dbl> <dbl>
## 1 New England        33 0.0602   6  
## 2 Middle Atlantic    57 0.104   10.4
## 3 E. Nor. Central   119 0.217   21.7
## 4 W. Nor. Central    36 0.0657   6.6
## 5 South Atlantic    121 0.221   22.1
## 6 E. Sou. Central    35 0.0639   6.4
## 7 W. Sou. Central    57 0.104   10.4
## 8 Mountain           35 0.0639   6.4
## 9 Pacific            55 0.100   10
\end{verbatim}

Now, I can rest easy knowing that I can find the percentage of 2012-Obama supporting Protestants with children who reside in the South Atlantic census region (29.2\%).

\hypertarget{practice-exploring-data}{%
\section{Practice Exploring Data}\label{practice-exploring-data}}

You can see here that the \texttt{dplyr} functions provide an enormous amount of flexibility and power.

Use the remainder of class time today to explore the \texttt{gss\_sm} data. Try summarizing different variables according to different groupings. Try using other measures like \texttt{mean()} or \texttt{sd()} to summarize numeric variables (like the number of children).

You may be feeling overwhelmed at the moment - don't despair, we're going to continue practicing these skills throughout the remainder of the course.

\hypertarget{homework-2}{%
\chapter*{Homework 2}\label{homework-2}}
\addcontentsline{toc}{chapter}{Homework 2}

\textbf{Due Date:} Sunday, 25 February by 23:59:59

\textbf{Submission Instructions:} Submit your completed R script file to Moodle.

To be posted by Wednesday, February 14.

  \bibliography{book.bib,packages.bib}

\end{document}
