<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Using the Tidyverse to Summarize | Statistical Programming for the Social Sciences Using R</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Using the Tidyverse to Summarize | Statistical Programming for the Social Sciences Using R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="github-repo" content="wstubenbord/ScPoSPSSUR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Using the Tidyverse to Summarize | Statistical Programming for the Social Sciences Using R" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="Wesley Stubenbord" />


<meta name="date" content="2024-02-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="homework-1.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistical Programming for the Social Sciences</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> An Introduction to <code>R</code></a>
<ul>
<li class="chapter" data-level="1.1" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#installing-r"><i class="fa fa-check"></i><b>1.1</b> Installing <code>R</code></a></li>
<li class="chapter" data-level="1.2" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#installing-rstudio"><i class="fa fa-check"></i><b>1.2</b> Installing RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#using-the-console"><i class="fa fa-check"></i><b>1.3</b> Using the Console</a></li>
<li class="chapter" data-level="1.4" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#calculations-with-variables"><i class="fa fa-check"></i><b>1.4</b> Calculations with Variables</a></li>
<li class="chapter" data-level="1.5" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#saving-your-work"><i class="fa fa-check"></i><b>1.5</b> Saving Your Work</a></li>
<li class="chapter" data-level="1.6" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#creating-and-saving-an-r-script"><i class="fa fa-check"></i><b>1.6</b> Creating and Saving an R Script</a></li>
<li class="chapter" data-level="1.7" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#interacting-in-an-r-script"><i class="fa fa-check"></i><b>1.7</b> Interacting in an R Script</a></li>
<li class="chapter" data-level="1.8" data-path="an-introduction-to-r.html"><a href="an-introduction-to-r.html#summary"><i class="fa fa-check"></i><b>1.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html"><i class="fa fa-check"></i><b>2</b> Working with Data in <code>R</code></a>
<ul>
<li class="chapter" data-level="2.1" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html#functions"><i class="fa fa-check"></i><b>2.1</b> Functions</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html#calling-a-function"><i class="fa fa-check"></i><b>2.1.1</b> Calling a Function</a></li>
<li class="chapter" data-level="2.1.2" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html#using-arguments-in-a-function"><i class="fa fa-check"></i><b>2.1.2</b> Using Arguments in a Function</a></li>
<li class="chapter" data-level="2.1.3" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html#getting-help-with-functions"><i class="fa fa-check"></i><b>2.1.3</b> Getting Help with Functions</a></li>
<li class="chapter" data-level="" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html#check-your-understanding"><i class="fa fa-check"></i>Check Your Understanding:</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html#packages"><i class="fa fa-check"></i><b>2.2</b> Packages</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html#installing-packages"><i class="fa fa-check"></i><b>2.2.1</b> Installing Packages</a></li>
<li class="chapter" data-level="2.2.2" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html#loading-libraries"><i class="fa fa-check"></i><b>2.2.2</b> Loading Libraries</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html#loading-data"><i class="fa fa-check"></i><b>2.3</b> Loading Data</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html#using-data-from-packages"><i class="fa fa-check"></i><b>2.3.1</b> Using Data from Packages</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html#data-types-and-data-structures"><i class="fa fa-check"></i><b>2.4</b> Data Types and Data Structures</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html#data-types"><i class="fa fa-check"></i><b>2.4.1</b> Data Types</a></li>
<li class="chapter" data-level="2.4.2" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html#data-structures"><i class="fa fa-check"></i><b>2.4.2</b> Data Structures</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="working-with-data-in-r.html"><a href="working-with-data-in-r.html#using-functions-with-data"><i class="fa fa-check"></i><b>2.5</b> Using Functions with Data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="homework-1.html"><a href="homework-1.html"><i class="fa fa-check"></i>Homework 1</a></li>
<li class="chapter" data-level="3" data-path="using-the-tidyverse-to-summarize.html"><a href="using-the-tidyverse-to-summarize.html"><i class="fa fa-check"></i><b>3</b> Using the Tidyverse to Summarize</a>
<ul>
<li class="chapter" data-level="3.1" data-path="using-the-tidyverse-to-summarize.html"><a href="using-the-tidyverse-to-summarize.html#basic-description-with-base-r"><i class="fa fa-check"></i><b>3.1</b> Basic Description with Base R</a></li>
<li class="chapter" data-level="3.2" data-path="using-the-tidyverse-to-summarize.html"><a href="using-the-tidyverse-to-summarize.html#the-pipe-operator"><i class="fa fa-check"></i><b>3.2</b> The Pipe Operator</a></li>
<li class="chapter" data-level="3.3" data-path="using-the-tidyverse-to-summarize.html"><a href="using-the-tidyverse-to-summarize.html#dplyr"><i class="fa fa-check"></i><b>3.3</b> <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="using-the-tidyverse-to-summarize.html"><a href="using-the-tidyverse-to-summarize.html#functions-from-dplyr"><i class="fa fa-check"></i><b>3.3.1</b> Functions from <code>dplyr</code></a></li>
<li class="chapter" data-level="3.3.2" data-path="using-the-tidyverse-to-summarize.html"><a href="using-the-tidyverse-to-summarize.html#glimpsing-gss-data"><i class="fa fa-check"></i><b>3.3.2</b> Glimpsing GSS Data</a></li>
<li class="chapter" data-level="3.3.3" data-path="using-the-tidyverse-to-summarize.html"><a href="using-the-tidyverse-to-summarize.html#selecting-columns"><i class="fa fa-check"></i><b>3.3.3</b> Selecting Columns</a></li>
<li class="chapter" data-level="3.3.4" data-path="using-the-tidyverse-to-summarize.html"><a href="using-the-tidyverse-to-summarize.html#grouping-and-summarizing"><i class="fa fa-check"></i><b>3.3.4</b> Grouping and Summarizing</a></li>
<li class="chapter" data-level="3.3.5" data-path="using-the-tidyverse-to-summarize.html"><a href="using-the-tidyverse-to-summarize.html#calculating-with-mutate"><i class="fa fa-check"></i><b>3.3.5</b> Calculating with <code>mutate()</code></a></li>
<li class="chapter" data-level="3.3.6" data-path="using-the-tidyverse-to-summarize.html"><a href="using-the-tidyverse-to-summarize.html#filtering"><i class="fa fa-check"></i><b>3.3.6</b> Filtering</a></li>
<li class="chapter" data-level="3.3.7" data-path="using-the-tidyverse-to-summarize.html"><a href="using-the-tidyverse-to-summarize.html#all-together-now"><i class="fa fa-check"></i><b>3.3.7</b> All Together Now</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="using-the-tidyverse-to-summarize.html"><a href="using-the-tidyverse-to-summarize.html#some-data-exploration"><i class="fa fa-check"></i><b>3.4</b> Some Data Exploration</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Programming for the Social Sciences Using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="using-the-tidyverse-to-summarize" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Using the Tidyverse to Summarize<a href="using-the-tidyverse-to-summarize.html#using-the-tidyverse-to-summarize" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In the previous chapter, you learned how to load data from a package, how to access a column from a tibble using the subset operator <code>$</code>, and how to use basic functions to answer questions like: what was the total number of votes cast in the 2016 U.S. presidential election?</p>
<p>We’ve had a couple strokes of luck so far, however. Namely, our data has been nice and tidy and our questions haven’t required us to poke around in our data to get the answers we are interested in. This brings us to <em>data wrangling</em> - the art and science of manipulating, distilling, or cajoling data into a format that allows you to find the answers you are seeking.<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></p>
<p>For this lesson, we are going to maintain the illusion of neat and tidy data and focus on learning the tools necessary to dig into a data set: in particular, <code>dplyr</code> and the <strong>pipe operator</strong>. In the next lesson, our luck will unfortunately run out and we will be confronted with the harsh reality of unseemly data.<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a></p>
<div id="basic-description-with-base-r" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Basic Description with Base R<a href="using-the-tidyverse-to-summarize.html#basic-description-with-base-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s use an example to get us started. Last class, you toyed around with the 2016 U.S. presidential election data from the <code>socviz</code> package, a helpful collection of data sets and other goodies assembled by Kieran Healy.<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a></p>
<p>We’ll use another data set from the same package in a moment, but, for now, let’s start again with the <code>election</code> data. We’re also going to re-load our new best friend, the <em>tidyverse</em>.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="using-the-tidyverse-to-summarize.html#cb46-1" tabindex="-1"></a><span class="fu">library</span>(socviz)</span>
<span id="cb46-2"><a href="using-the-tidyverse-to-summarize.html#cb46-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<p>Libraries loaded. Remember, once you have the packages installed, you don’t have to do it again. So no need to include <code>install.packages()</code> in your script going forward.<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a></p>
<p>We’ll load the data into an object in our environment. This time, I’m going to use a shorter name for the tibble to spare myself future pain. Longer names mean more to retype later.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="using-the-tidyverse-to-summarize.html#cb47-1" tabindex="-1"></a>elec_2016 <span class="ot">&lt;-</span> election</span></code></pre></div>
<p>Just like last time, we can do basic calculations on columns. We can even throw in a few new functions for good measure:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="using-the-tidyverse-to-summarize.html#cb48-1" tabindex="-1"></a><span class="co"># table() gives a contingency table for character variables.</span></span>
<span id="cb48-2"><a href="using-the-tidyverse-to-summarize.html#cb48-2" tabindex="-1"></a><span class="co"># Here it&#39;s giving the number of states (plus D.C.) won by each candidate.</span></span>
<span id="cb48-3"><a href="using-the-tidyverse-to-summarize.html#cb48-3" tabindex="-1"></a><span class="fu">table</span>(elec_2016<span class="sc">$</span>winner)</span></code></pre></div>
<pre><code>## 
## Clinton   Trump 
##      21      30</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="using-the-tidyverse-to-summarize.html#cb50-1" tabindex="-1"></a><span class="co"># Wrapping prop.table() around a contingency table gives relative frequencies.</span></span>
<span id="cb50-2"><a href="using-the-tidyverse-to-summarize.html#cb50-2" tabindex="-1"></a><span class="co"># i.e., Hillary Clinton won 41.2% of states (plus Washington D.C.) or 21/51.</span></span>
<span id="cb50-3"><a href="using-the-tidyverse-to-summarize.html#cb50-3" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(elec_2016<span class="sc">$</span>winner))</span></code></pre></div>
<pre><code>## 
##   Clinton     Trump 
## 0.4117647 0.5882353</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="using-the-tidyverse-to-summarize.html#cb52-1" tabindex="-1"></a><span class="co"># summary() gives us a nice 5-number summary for numeric variables.</span></span>
<span id="cb52-2"><a href="using-the-tidyverse-to-summarize.html#cb52-2" tabindex="-1"></a><span class="co"># Here we see the min, max, median, mean, and quartiles for the pop. vote margin.</span></span>
<span id="cb52-3"><a href="using-the-tidyverse-to-summarize.html#cb52-3" tabindex="-1"></a><span class="fu">summary</span>(elec_2016<span class="sc">$</span>vote_margin)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    2736   96382  212030  383997  522207 4269978</code></pre>
<p>But, what if I want to do something more specific?</p>
<p>What if, for instance, I really want to know how much of the popular vote third party Libertarian candidate Gary Johnson won across the different regions of the United States? Here, we need special functions from dplyr and the pipe operator.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="using-the-tidyverse-to-summarize.html#cb54-1" tabindex="-1"></a><span class="co"># An illustrative example - no need to try this just yet</span></span>
<span id="cb54-2"><a href="using-the-tidyverse-to-summarize.html#cb54-2" tabindex="-1"></a>elec_2016 <span class="sc">%&gt;%</span></span>
<span id="cb54-3"><a href="using-the-tidyverse-to-summarize.html#cb54-3" tabindex="-1"></a>  <span class="fu">group_by</span>(census) <span class="sc">%&gt;%</span></span>
<span id="cb54-4"><a href="using-the-tidyverse-to-summarize.html#cb54-4" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total =</span> <span class="fu">sum</span>(johnson_vote))</span></code></pre></div>
<pre><code>## # A tibble: 4 × 2
##   census      total
##   &lt;chr&gt;       &lt;dbl&gt;
## 1 Midwest   1203062
## 2 Northeast  676192
## 3 South     1370056
## 4 West      1239925</code></pre>
<p><img src="docs/_main_files/figure-html/ceci_pipe.png" width="149" /></p>
</div>
<div id="the-pipe-operator" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> The Pipe Operator<a href="using-the-tidyverse-to-summarize.html#the-pipe-operator" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <strong>pipe operator</strong> is a very handy tool indeed. It is a specialized operator that comes from the <code>maggritr</code> package, which itself is contained in the tidyverse.</p>
<p>It looks like this: <code>%&gt;%</code>. But, it can also look like this: <code>|&gt;</code>. There isn’t much of a difference between the two, so you can use whichever you prefer as long as you are consistent.</p>
<p>The pipe operator has a straightforward function: it allows you to combine a series of steps into a single line of code. And, it does this in a way that makes your code very legible. Whenever you see the pipe operator, you should read it as though it is saying, “And then [do this].”</p>
<p>So in the previous example I gave you might read it as:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="using-the-tidyverse-to-summarize.html#cb56-1" tabindex="-1"></a>elec_2016 <span class="sc">%&gt;%</span>                            <span class="co"># Take the election data AND THEN</span></span>
<span id="cb56-2"><a href="using-the-tidyverse-to-summarize.html#cb56-2" tabindex="-1"></a>  <span class="fu">group_by</span>(census) <span class="sc">%&gt;%</span>                   <span class="co"># group it by census region AND THEN</span></span>
<span id="cb56-3"><a href="using-the-tidyverse-to-summarize.html#cb56-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total =</span> <span class="fu">sum</span>(johnson_vote))   <span class="co"># sum up the Johnson vote.</span></span></code></pre></div>
<p>Note a couple of things here:</p>
<ol style="list-style-type: decimal">
<li><p>The pipe operator always goes at the end of each line, followed by a new line</p></li>
<li><p>The pipe operator never goes at the end of the command</p></li>
</ol>
<p>The first is a convention to make code more readable and the second is a requirement. If you leave a pipe operator at the end of your statement, <code>R</code> will search for the missing code and then give you an unhappy error when you try to run more code. Don’t leave a pipe operator hanging.</p>
</div>
<div id="dplyr" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> <code>dplyr</code><a href="using-the-tidyverse-to-summarize.html#dplyr" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="functions-from-dplyr" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Functions from <code>dplyr</code><a href="using-the-tidyverse-to-summarize.html#functions-from-dplyr" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><code>dplyr</code> (pronounced dee-ply-R) is a handy set of tools for working with tabular data. It’s one of the packages in tidyverse (along with <code>ggplot2</code>, <code>tidyr</code>, <code>tibble</code>, <code>readr</code>, and a few others), so you don’t have to load it separately.</p>
<p><code>dplyr</code> has a handful of special functions:</p>
<ul>
<li><p><code>group_by()</code>, which groups data together at the level we desire (such as states by census region in our example).</p></li>
<li><p><code>filter()</code>, which gives us the rows corresponding to some criteria entered as an argument</p></li>
<li><p><code>select()</code>, which selects columns</p></li>
<li><p><code>summarize()</code>, which performs calculations</p></li>
<li><p><code>mutate()</code>, which creates new columns (e.g., variables)</p></li>
</ul>
</div>
<div id="glimpsing-gss-data" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Glimpsing GSS Data<a href="using-the-tidyverse-to-summarize.html#glimpsing-gss-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s load another data set from <code>socviz</code>. This one is called <code>gss_sm</code> and contains a nice, clean extract from the 2016 General Social Survey.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="using-the-tidyverse-to-summarize.html#cb57-1" tabindex="-1"></a>gss <span class="ot">&lt;-</span> gss_sm</span></code></pre></div>
<p>The <a href="https://gss.norc.org/">General Social Survey</a> is a nationally representative biennial survey of U.S. adults on sociological topics produced out of the National Opinion Research Center (NORC) at the University of Chicago since 1972.</p>
<p>Take a quick look at the data. You can use <code>glimpse()</code>, another <code>dplyr</code> function, to get a good look at it and you can look at it visually using <code>view()</code>. Typing in <code>?gss_sm</code> (the original name of the data set from the package) will tell you what the variables are.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="using-the-tidyverse-to-summarize.html#cb58-1" tabindex="-1"></a><span class="fu">glimpse</span>(gss)</span></code></pre></div>
<p>As you might notice, there’s a wealth of data in here. You might also notice that the data is at the <em>individual-level</em>. In this data, each row represents a individual respondent and each column is a variable (or their response to a question).</p>
</div>
<div id="selecting-columns" class="section level3 hasAnchor" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> Selecting Columns<a href="using-the-tidyverse-to-summarize.html#selecting-columns" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Maybe I want to narrow in and look at just a few variables. I can use the <code>select()</code> function to do this.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="using-the-tidyverse-to-summarize.html#cb59-1" tabindex="-1"></a>gss <span class="sc">%&gt;%</span></span>
<span id="cb59-2"><a href="using-the-tidyverse-to-summarize.html#cb59-2" tabindex="-1"></a>  <span class="fu">select</span>(id, sex, religion)</span></code></pre></div>
<pre><code>## # A tibble: 2,867 × 3
##       id sex    religion  
##    &lt;dbl&gt; &lt;fct&gt;  &lt;fct&gt;     
##  1     1 Male   None      
##  2     2 Male   None      
##  3     3 Male   Catholic  
##  4     4 Female Catholic  
##  5     5 Female None      
##  6     6 Female None      
##  7     7 Male   None      
##  8     8 Female Catholic  
##  9     9 Male   Protestant
## 10    10 Male   None      
## # ℹ 2,857 more rows</code></pre>
<p>It returned a tibble with just the three variables I wanted to look at. I can always save a copy of this output if I want to, by storing it in a new object:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="using-the-tidyverse-to-summarize.html#cb61-1" tabindex="-1"></a>gender_rel <span class="ot">&lt;-</span> gss <span class="sc">%&gt;%</span></span>
<span id="cb61-2"><a href="using-the-tidyverse-to-summarize.html#cb61-2" tabindex="-1"></a>  <span class="fu">select</span>(id, sex, religion)</span></code></pre></div>
<p>And, if I decided I don’t want this copy, I can always get rid of it using the <code>rm()</code> function.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="using-the-tidyverse-to-summarize.html#cb62-1" tabindex="-1"></a><span class="fu">rm</span>(gender_rel)</span></code></pre></div>
</div>
<div id="grouping-and-summarizing" class="section level3 hasAnchor" number="3.3.4">
<h3><span class="header-section-number">3.3.4</span> Grouping and Summarizing<a href="using-the-tidyverse-to-summarize.html#grouping-and-summarizing" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s say we want to summarize our respondents by religious affiliation.</p>
<p>To do this, we first have to tell the computer how we are going to group the data. Grouping doesn’t change the data, but it prepares <code>R</code> to interpret it according to our groups. We’re going to group by the <code>religion</code> variable.</p>
<p>Next, we have to tell the computer how to <code>summarize()</code> the groups. We’re going to count the respondents using <code>n()</code>. <code>n()</code> just counts the rows within each group.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="using-the-tidyverse-to-summarize.html#cb63-1" tabindex="-1"></a>gss <span class="sc">%&gt;%</span></span>
<span id="cb63-2"><a href="using-the-tidyverse-to-summarize.html#cb63-2" tabindex="-1"></a>  <span class="fu">group_by</span>(religion) <span class="sc">%&gt;%</span>      <span class="co"># Group by religion</span></span>
<span id="cb63-3"><a href="using-the-tidyverse-to-summarize.html#cb63-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total =</span> <span class="fu">n</span>())      <span class="co"># Create a total by counting the rows</span></span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   religion   total
##   &lt;fct&gt;      &lt;int&gt;
## 1 Protestant  1371
## 2 Catholic     649
## 3 Jewish        51
## 4 None         619
## 5 Other        159
## 6 &lt;NA&gt;          18</code></pre>
<p>As you can see, <code>summarize()</code> needs you to provide a new column name and a measurement. In the example above, we gave the column the name <code>total</code> and asked it count the total number of respondents by group using the <code>n()</code> function.</p>
<p>Again, if we wanted to, we could save a copy of this summary in a new table as in the command below. Our original table will always be untouched unless we save over it (e.g., <code>gss &lt;- gss %&gt;% ...</code>).</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="using-the-tidyverse-to-summarize.html#cb65-1" tabindex="-1"></a>relig <span class="ot">&lt;-</span> gss <span class="sc">%&gt;%</span></span>
<span id="cb65-2"><a href="using-the-tidyverse-to-summarize.html#cb65-2" tabindex="-1"></a>  <span class="fu">group_by</span>(religion) <span class="sc">%&gt;%</span></span>
<span id="cb65-3"><a href="using-the-tidyverse-to-summarize.html#cb65-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total =</span> <span class="fu">n</span>())</span></code></pre></div>
<p>We can also group by two columns, such that we could find religious affiliation by sex, for example:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="using-the-tidyverse-to-summarize.html#cb66-1" tabindex="-1"></a>gss <span class="sc">%&gt;%</span></span>
<span id="cb66-2"><a href="using-the-tidyverse-to-summarize.html#cb66-2" tabindex="-1"></a>  <span class="fu">group_by</span>(religion, sex) <span class="sc">%&gt;%</span></span>
<span id="cb66-3"><a href="using-the-tidyverse-to-summarize.html#cb66-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;religion&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre><code>## # A tibble: 12 × 3
## # Groups:   religion [6]
##    religion   sex    total
##    &lt;fct&gt;      &lt;fct&gt;  &lt;int&gt;
##  1 Protestant Male     559
##  2 Protestant Female   812
##  3 Catholic   Male     287
##  4 Catholic   Female   362
##  5 Jewish     Male      22
##  6 Jewish     Female    29
##  7 None       Male     339
##  8 None       Female   280
##  9 Other      Male      58
## 10 Other      Female   101
## 11 &lt;NA&gt;       Male      11
## 12 &lt;NA&gt;       Female     7</code></pre>
<p>The ordering of the groups matters. Because religion came first in our <code>group()</code> function, our results will show us the number of protestants who are male and the number of protestants who are female. For a count, this is the same thing as the reverse (e.g., the number of protestants who are male is the number of males who are protestant), but for frequencies this is not the case and the order does matter.</p>
</div>
<div id="calculating-with-mutate" class="section level3 hasAnchor" number="3.3.5">
<h3><span class="header-section-number">3.3.5</span> Calculating with <code>mutate()</code><a href="using-the-tidyverse-to-summarize.html#calculating-with-mutate" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s add a frequency column and a percentage column so that we can get a sense of whether there the gender composition within religious groups.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="using-the-tidyverse-to-summarize.html#cb69-1" tabindex="-1"></a>gss <span class="sc">%&gt;%</span></span>
<span id="cb69-2"><a href="using-the-tidyverse-to-summarize.html#cb69-2" tabindex="-1"></a>  <span class="fu">group_by</span>(religion, sex) <span class="sc">%&gt;%</span></span>
<span id="cb69-3"><a href="using-the-tidyverse-to-summarize.html#cb69-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb69-4"><a href="using-the-tidyverse-to-summarize.html#cb69-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">freq =</span> total <span class="sc">/</span> <span class="fu">sum</span>(total),</span>
<span id="cb69-5"><a href="using-the-tidyverse-to-summarize.html#cb69-5" tabindex="-1"></a>         <span class="at">pct =</span> <span class="fu">round</span>((freq<span class="sc">*</span><span class="dv">100</span>), <span class="dv">1</span>))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;religion&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre><code>## # A tibble: 12 × 5
## # Groups:   religion [6]
##    religion   sex    total  freq   pct
##    &lt;fct&gt;      &lt;fct&gt;  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 Protestant Male     559 0.408  40.8
##  2 Protestant Female   812 0.592  59.2
##  3 Catholic   Male     287 0.442  44.2
##  4 Catholic   Female   362 0.558  55.8
##  5 Jewish     Male      22 0.431  43.1
##  6 Jewish     Female    29 0.569  56.9
##  7 None       Male     339 0.548  54.8
##  8 None       Female   280 0.452  45.2
##  9 Other      Male      58 0.365  36.5
## 10 Other      Female   101 0.635  63.5
## 11 &lt;NA&gt;       Male      11 0.611  61.1
## 12 &lt;NA&gt;       Female     7 0.389  38.9</code></pre>
<p>Notice, we used the same code as before, but we added a <code>mutate()</code> function which created two new columns <code>freq</code> and <code>pct</code>.
We also told the <code>mutate()</code> function how to calculate the columns. <code>freq</code>, we said, should be the respondents in each group divided by the sum of the groups (or <code>freq = total / sum(total)</code>) and <code>pct</code> should be the frequency multiplied by 100 and rounded to the first decimal place, using the <code>round()</code> helper function. In doing so, we find that among Protestant respondents, 40.8% are male and 59.2% are female.</p>
<p>Calculating relative frequencies can be a bit of a beast, but the general form is always the same.</p>
</div>
<div id="filtering" class="section level3 hasAnchor" number="3.3.6">
<h3><span class="header-section-number">3.3.6</span> Filtering<a href="using-the-tidyverse-to-summarize.html#filtering" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>What if we only wish to see the Protestant results of our last query? We can add a <code>filter()</code> function at the end.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="using-the-tidyverse-to-summarize.html#cb72-1" tabindex="-1"></a>gss <span class="sc">%&gt;%</span></span>
<span id="cb72-2"><a href="using-the-tidyverse-to-summarize.html#cb72-2" tabindex="-1"></a>  <span class="fu">group_by</span>(religion, sex) <span class="sc">%&gt;%</span></span>
<span id="cb72-3"><a href="using-the-tidyverse-to-summarize.html#cb72-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb72-4"><a href="using-the-tidyverse-to-summarize.html#cb72-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">freq =</span> total <span class="sc">/</span> <span class="fu">sum</span>(total),</span>
<span id="cb72-5"><a href="using-the-tidyverse-to-summarize.html#cb72-5" tabindex="-1"></a>         <span class="at">pct =</span> <span class="fu">round</span>((freq<span class="sc">*</span><span class="dv">100</span>), <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb72-6"><a href="using-the-tidyverse-to-summarize.html#cb72-6" tabindex="-1"></a>  <span class="fu">filter</span>(religion <span class="sc">==</span> <span class="st">&quot;Protestant&quot;</span>)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;religion&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre><code>## # A tibble: 2 × 5
## # Groups:   religion [1]
##   religion   sex    total  freq   pct
##   &lt;fct&gt;      &lt;fct&gt;  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Protestant Male     559 0.408  40.8
## 2 Protestant Female   812 0.592  59.2</code></pre>
<p>Usually, you’ll want to use a <code>filter()</code> function at the beginning of your query. It can save some code later on.</p>
<p>Here’s another example of <code>filter()</code>. This time, I’m only interested in religious affiliation among holders of graduate degrees.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="using-the-tidyverse-to-summarize.html#cb75-1" tabindex="-1"></a>gss <span class="sc">%&gt;%</span></span>
<span id="cb75-2"><a href="using-the-tidyverse-to-summarize.html#cb75-2" tabindex="-1"></a>  <span class="fu">filter</span>(degree <span class="sc">==</span> <span class="st">&#39;Graduate&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb75-3"><a href="using-the-tidyverse-to-summarize.html#cb75-3" tabindex="-1"></a>  <span class="fu">group_by</span>(religion) <span class="sc">%&gt;%</span></span>
<span id="cb75-4"><a href="using-the-tidyverse-to-summarize.html#cb75-4" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb75-5"><a href="using-the-tidyverse-to-summarize.html#cb75-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">freq =</span> total <span class="sc">/</span> <span class="fu">sum</span>(total),</span>
<span id="cb75-6"><a href="using-the-tidyverse-to-summarize.html#cb75-6" tabindex="-1"></a>         <span class="at">pct =</span> <span class="fu">round</span>((freq<span class="sc">*</span><span class="dv">100</span>), <span class="dv">1</span>))</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##   religion   total    freq   pct
##   &lt;fct&gt;      &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1 Protestant   126 0.396    39.6
## 2 Catholic      63 0.198    19.8
## 3 Jewish        15 0.0472    4.7
## 4 None          82 0.258    25.8
## 5 Other         31 0.0975    9.7
## 6 &lt;NA&gt;           1 0.00314   0.3</code></pre>
<p>And, so here I see that 39.6% of graduate-degree holding respondents were Protestant and 25.8% had no religious affiliation. Later on, we’ll learn how to turn this sort of thing into a graph.</p>
</div>
<div id="all-together-now" class="section level3 hasAnchor" number="3.3.7">
<h3><span class="header-section-number">3.3.7</span> All Together Now<a href="using-the-tidyverse-to-summarize.html#all-together-now" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>What if I want to do something like find all survey respondents who are Protestant, voted for Obama in the 2012 U.S. Presidential election, and have children? And I’d like to know their relative frequency across regions of the U.S.?</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="using-the-tidyverse-to-summarize.html#cb77-1" tabindex="-1"></a>gss <span class="sc">%&gt;%</span></span>
<span id="cb77-2"><a href="using-the-tidyverse-to-summarize.html#cb77-2" tabindex="-1"></a>  <span class="fu">filter</span>(religion <span class="sc">==</span> <span class="st">&quot;Protestant&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb77-3"><a href="using-the-tidyverse-to-summarize.html#cb77-3" tabindex="-1"></a>  <span class="fu">filter</span>(obama <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb77-4"><a href="using-the-tidyverse-to-summarize.html#cb77-4" tabindex="-1"></a>  <span class="fu">filter</span>(childs <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb77-5"><a href="using-the-tidyverse-to-summarize.html#cb77-5" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span></span>
<span id="cb77-6"><a href="using-the-tidyverse-to-summarize.html#cb77-6" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb77-7"><a href="using-the-tidyverse-to-summarize.html#cb77-7" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">freq =</span> <span class="fu">round</span>(total <span class="sc">/</span> <span class="fu">sum</span>(total),<span class="dv">4</span>),</span>
<span id="cb77-8"><a href="using-the-tidyverse-to-summarize.html#cb77-8" tabindex="-1"></a>         <span class="at">pct =</span> <span class="fu">round</span>((freq<span class="sc">*</span><span class="dv">100</span>), <span class="dv">1</span>))</span></code></pre></div>
<pre><code>## # A tibble: 9 × 4
##   region          total   freq   pct
##   &lt;fct&gt;           &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1 New England        15 0.0409   4.1
## 2 Middle Atlantic    27 0.0736   7.4
## 3 E. Nor. Central    79 0.215   21.5
## 4 W. Nor. Central    19 0.0518   5.2
## 5 South Atlantic    107 0.292   29.2
## 6 E. Sou. Central    31 0.0845   8.5
## 7 W. Sou. Central    40 0.109   10.9
## 8 Mountain           24 0.0654   6.5
## 9 Pacific            25 0.0681   6.8</code></pre>
<p>Now, I can rest easy knowing that I can find the percentage of 2012-Obama supporting Protestants with children who reside in the South Atlantic census region (29.2%).</p>
</div>
</div>
<div id="some-data-exploration" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Some Data Exploration<a href="using-the-tidyverse-to-summarize.html#some-data-exploration" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Use the remainder of class time today to explore the gss_sm dataset. Try summarizing a few different variables according to different groups</p>

</div>
</div>












<div class="footnotes">
<hr />
<ol start="3">
<li id="fn3"><p>Data wrangling, if it can be defined, is as an expansive topic. We’ll focus on summarizing data today.<a href="using-the-tidyverse-to-summarize.html#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p>Sadly, almost all data you encounter out in the wild will be very unseemly for one reason or another. But, maybe after taking this course and ascending the ranks of government/business/academia, you too will become an evangelical for orderly data and help bring peace to a world of mismanaged data.<a href="using-the-tidyverse-to-summarize.html#fnref4" class="footnote-back">↩︎</a></p></li>
<li id="fn5"><p>The <code>socviz</code> package serves as an accompaniment to Healy’s textbook, <em>Data Visualization</em>, which is highly recommended.<a href="using-the-tidyverse-to-summarize.html#fnref5" class="footnote-back">↩︎</a></p></li>
<li id="fn6"><p>Anytime you do install packages, do it directly in the console. If someone needs to run your code, they should see the <code>library()</code> calls in the beginning of your code (after your header) and will know whether they need to install additional packages or not.</p>
<p>Alternatively, instead of using the <code>library()</code> function, you can always use the <code>require()</code> function, which has the benefit of both loading packages if you do have them and installing them if you don’t.<a href="using-the-tidyverse-to-summarize.html#fnref6" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="homework-1.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/wstubenbord/ScPoSPSSUR/edit/main/04-using-the-tidyverse.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
